import Foundation
import SystemPackage

/// Helpers for locating payment address files on disk.
///
/// Payment addresses generated by `scm` are saved as `<name>.payment.addr`, but users
/// may also bring their own enterprise (payment-only) addresses saved as `<name>.addr`,
/// with matching `<name>.skey` / `<name>.vkey` key files. Every lookup accepts both
/// layouts, preferring the `.payment.addr` form when both exist.
enum PaymentAddressFiles {
    /// File name suffixes that identify a stake address file (never a payment address).
    private static let stakeSuffix = ".stake.addr"

    /// Suffixes stripped from a user-supplied name or file name to get the bare address name.
    private static let strippableSuffixes = [".payment.addr", ".stake.addr", ".addr", ".payment", ".stake"]

    /// Whether `fileName` looks like a payment address file (`name.payment.addr` or `name.addr`).
    static func isPaymentAddressFile(_ fileName: String) -> Bool {
        fileName.hasSuffix(".addr") && !fileName.hasSuffix(stakeSuffix)
    }

    /// The bare address name for a name or file name, e.g. `owner.payment.addr` → `owner`,
    /// `owner.addr` → `owner`, `owner.payment` → `owner`, `owner` → `owner`.
    static func stem(of nameOrFileName: String) -> String {
        for suffix in strippableSuffixes where nameOrFileName.hasSuffix(suffix) {
            return String(nameOrFileName.dropLast(suffix.count))
        }
        return nameOrFileName
    }

    /// Candidate payment address file names for `name`, in lookup priority order.
    static func candidateFileNames(for name: String) -> [String] {
        let base = stem(of: name)
        return ["\(base).payment.addr", "\(base).addr"]
    }

    /// The first existing payment address file for `name` inside `directory`, if any.
    static func resolve(
        name: String,
        in directory: FilePath,
        fileManager: FileManager = .default
    ) -> FilePath? {
        candidateFileNames(for: name)
            .map { directory.appending($0) }
            .first { fileManager.fileExists(atPath: $0.string) }
    }

    /// All payment address files in `directory`, sorted by name.
    static func list(in directory: FilePath, fileManager: FileManager = .default) throws -> [String] {
        try fileManager.contentsOfDirectory(atPath: directory.string)
            .filter(isPaymentAddressFile)
            .sorted()
    }
}
